"""Add saved_posts table and user_id to posts

Revision ID: 3929ccb53095
Revises: b57b49619a94
Create Date: 2024-07-22 09:40:54.003278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3929ccb53095'
down_revision: Union[str, None] = 'b57b49619a94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Drop the foreign key constraint
    op.drop_constraint('posts_user_id_fkey', 'posts', type_='foreignkey')
    
    # Drop the tables
    op.drop_table('saved_posts')
    op.drop_table('users')
    op.drop_table('posts')


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('image_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('caption', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='posts_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='posts_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('users',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('password', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('saved_posts',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('post_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name='saved_posts_post_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='saved_posts_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='saved_posts_pkey')
    )
    # ### end Alembic commands ###
