"""Add created_at and updated_at to Post and SavedModel

Revision ID: e2522cb35057
Revises: 3929ccb53095
Create Date: 2024-07-22 21:18:18.409507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e2522cb35057'
down_revision: Union[str, None] = '3929ccb53095'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
   # Add columns to the posts table
    op.add_column('posts', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now()))
    op.add_column('posts', sa.Column('updated_at', sa.DateTime(timezone=True), onupdate=sa.func.now()))
    
    # Add columns to the saved_posts table
    op.add_column('saved_posts', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now()))
    op.add_column('saved_posts', sa.Column('updated_at', sa.DateTime(timezone=True), onupdate=sa.func.now()))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('password', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('saved_posts',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('post_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name='saved_posts_post_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='saved_posts_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='saved_posts_pkey')
    )
    op.create_table('posts',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('image_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('caption', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='posts_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='posts_pkey')
    )
    # ### end Alembic commands ###
